- type: entity
  id: StandardCrescentStation #Main faction stations
  parent:
    - BaseStation
    - BaseStationCargo
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationShuttles
    - BaseStationAlertLevels
    - BaseStationSiliconLawCrescentStation
    - BaseStationEmpImmune
    - BaseStationSectorNews
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

- type: entity
  id: StandardCrescentOutpost #POI
  parent:
    - BaseStation
    - BaseStationCargo
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationShuttles
    - BaseStationAlertLevels
    - BaseStationSiliconLawCrescentStation
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

- type: entity
  id: StandardCrescentVessel #Combat vessel
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationCargo
    - BaseCombatShipAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationRenameFaxes
    - BaseStationRenameWarpPoints
    - BaseStationSiliconLawCrescentShips
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

- type: entity
  id: StandardCrescentCivilianVessel #Civilian / unarmed vessel
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationRenameFaxes
    - BaseStationCargo
    - BaseStationRenameWarpPoints
    - BaseStationSiliconLawCrescentShips
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

- type: entity
  id: StandardCrescentExpeditionVessel #Expeds
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationRenameFaxes
    - BaseStationCargo
    - BaseStationRenameWarpPoints
    - BaseStationSiliconLawCrescentShips
    - BaseStationExpeditions
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

- type: entity
  id: StandardCrescentExpeditionVesselCombat #Expeds
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseCombatShipAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationRenameFaxes
    - BaseStationCargo
    - BaseStationRenameWarpPoints
    - BaseStationSiliconLawCrescentShips
    - BaseStationExpeditions
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

- type: entity
  id: BaseStationSiliconLawCrescentStation
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Asimov

- type: entity
  id: BaseStationSiliconLawCrescentShips
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Asimov

- type: entity
  id: BaseStationRenameFaxes
  abstract: true
  components:
    - type: StationRenameFaxes

- type: entity
  id: BaseStationRenameWarpPoints
  abstract: true
  components:
    - type: StationRenameWarps

- type: entity
  id: BaseStationEmpImmune
  abstract: true
  components:
    - type: StationEmpImmune

# Sector-wide news access, should be on stations with comms (radio station, telecomms)
- type: entity
  id: BaseStationSectorNews
  abstract: true
  components:
    - type: SectorNews

- type: entity
  id: BaseCombatShipAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: combatShipAlerts
